name: Build and push image to Docker Hub

on:
  push:
    branches:
      - 'master'
    tags:
      -'latest'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: simatei/enketo-express-extra-widgets
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
